// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	interfaces "digital-wallet/internal/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// InTransaction is an autogenerated mock type for the InTransaction type
type InTransaction struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, repoRegistry
func (_m *InTransaction) Execute(ctx context.Context, repoRegistry interfaces.RegistryRepository) (interface{}, error) {
	ret := _m.Called(ctx, repoRegistry)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.RegistryRepository) (interface{}, error)); ok {
		return rf(ctx, repoRegistry)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.RegistryRepository) interface{}); ok {
		r0 = rf(ctx, repoRegistry)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interfaces.RegistryRepository) error); ok {
		r1 = rf(ctx, repoRegistry)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInTransaction creates a new instance of InTransaction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInTransaction(t interface {
	mock.TestingT
	Cleanup(func())
}) *InTransaction {
	mock := &InTransaction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
