// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	interfaces "digital-wallet/internal/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// RegistryRepository is an autogenerated mock type for the RegistryRepository type
type RegistryRepository struct {
	mock.Mock
}

// DoInTransaction provides a mock function with given fields: ctx, txFunc
func (_m *RegistryRepository) DoInTransaction(ctx context.Context, txFunc interfaces.InTransaction) (interface{}, error) {
	ret := _m.Called(ctx, txFunc)

	if len(ret) == 0 {
		panic("no return value specified for DoInTransaction")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.InTransaction) (interface{}, error)); ok {
		return rf(ctx, txFunc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.InTransaction) interface{}); ok {
		r0 = rf(ctx, txFunc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interfaces.InTransaction) error); ok {
		r1 = rf(ctx, txFunc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWalletRepository provides a mock function with no fields
func (_m *RegistryRepository) GetWalletRepository() interfaces.WalletRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetWalletRepository")
	}

	var r0 interfaces.WalletRepository
	if rf, ok := ret.Get(0).(func() interfaces.WalletRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.WalletRepository)
		}
	}

	return r0
}

// GetWalletTransactionRepository provides a mock function with no fields
func (_m *RegistryRepository) GetWalletTransactionRepository() interfaces.WalletTransactionRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetWalletTransactionRepository")
	}

	var r0 interfaces.WalletTransactionRepository
	if rf, ok := ret.Get(0).(func() interfaces.WalletTransactionRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.WalletTransactionRepository)
		}
	}

	return r0
}

// NewRegistryRepository creates a new instance of RegistryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegistryRepository {
	mock := &RegistryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
