// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	errors "github.com/pkg/errors"
	mock "github.com/stretchr/testify/mock"
)

// stackTracer is an autogenerated mock type for the stackTracer type
type stackTracer struct {
	mock.Mock
}

// StackTrace provides a mock function with no fields
func (_m *stackTracer) StackTrace() errors.StackTrace {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StackTrace")
	}

	var r0 errors.StackTrace
	if rf, ok := ret.Get(0).(func() errors.StackTrace); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.StackTrace)
		}
	}

	return r0
}

// newStackTracer creates a new instance of stackTracer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newStackTracer(t interface {
	mock.TestingT
	Cleanup(func())
}) *stackTracer {
	mock := &stackTracer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
