// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "digital-wallet/internal/models"
)

// WalletTransactionRepository is an autogenerated mock type for the WalletTransactionRepository type
type WalletTransactionRepository struct {
	mock.Mock
}

// CountByWalletID provides a mock function with given fields: ctx, walletID
func (_m *WalletTransactionRepository) CountByWalletID(ctx context.Context, walletID string) (int64, error) {
	ret := _m.Called(ctx, walletID)

	if len(ret) == 0 {
		panic("no return value specified for CountByWalletID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, walletID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, walletID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, walletID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, transaction
func (_m *WalletTransactionRepository) Create(ctx context.Context, transaction *models.WalletTransaction) error {
	ret := _m.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.WalletTransaction) error); ok {
		r0 = rf(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *WalletTransactionRepository) GetByID(ctx context.Context, id string) (*models.WalletTransaction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.WalletTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.WalletTransaction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.WalletTransaction); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WalletTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByWalletID provides a mock function with given fields: ctx, walletID, limit, offset
func (_m *WalletTransactionRepository) GetByWalletID(ctx context.Context, walletID string, limit int, offset int) ([]models.WalletTransaction, error) {
	ret := _m.Called(ctx, walletID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByWalletID")
	}

	var r0 []models.WalletTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]models.WalletTransaction, error)); ok {
		return rf(ctx, walletID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []models.WalletTransaction); ok {
		r0 = rf(ctx, walletID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WalletTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, walletID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, transaction
func (_m *WalletTransactionRepository) Update(ctx context.Context, transaction *models.WalletTransaction) error {
	ret := _m.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.WalletTransaction) error); ok {
		r0 = rf(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWalletTransactionRepository creates a new instance of WalletTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWalletTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WalletTransactionRepository {
	mock := &WalletTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
