// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "digital-wallet/internal/dto"

	mock "github.com/stretchr/testify/mock"

	models "digital-wallet/internal/models"
)

// WalletService is an autogenerated mock type for the WalletService type
type WalletService struct {
	mock.Mock
}

// GetBalance provides a mock function with given fields: ctx, userID
func (_m *WalletService) GetBalance(ctx context.Context, userID string) (*dto.BalanceResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *dto.BalanceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.BalanceResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.BalanceResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.BalanceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrCreateWallet provides a mock function with given fields: ctx, userID
func (_m *WalletService) GetOrCreateWallet(ctx context.Context, userID string) (*models.Wallet, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreateWallet")
	}

	var r0 *models.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Wallet, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Wallet); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionHistory provides a mock function with given fields: ctx, userID, limit, offset
func (_m *WalletService) GetTransactionHistory(ctx context.Context, userID string, limit int, offset int) ([]models.WalletTransaction, int64, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionHistory")
	}

	var r0 []models.WalletTransaction
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]models.WalletTransaction, int64, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []models.WalletTransaction); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WalletTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int64); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, userID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Withdraw provides a mock function with given fields: ctx, req
func (_m *WalletService) Withdraw(ctx context.Context, req dto.WithdrawRequest) (*dto.WithdrawResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 *dto.WithdrawResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.WithdrawRequest) (*dto.WithdrawResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.WithdrawRequest) *dto.WithdrawResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.WithdrawResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.WithdrawRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWalletService creates a new instance of WalletService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWalletService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WalletService {
	mock := &WalletService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
